### PR TITLE
Navigation fixes

### PR DESCRIPTION
**Pull request by tim-band**
Navigation no longer uses window.location.pathname, which is sensitive to the base path the front end is served on.
Mobile mode is fixed.
Breadcrumb code is simplified.

### CODE REVIEW

**Review by acholyn — COMMENTED** [review]
Looks good, I like the test updates, breadcrumbs work quite nicely but I have noticed something a bit odd, which may be intentional. When you first search a word and you go through occurrences then texts, if you continue through and select a new word from the text, it takes you to occurrences for that word but the breadcrumbs are still for the first word and the later breadcrumbs disappear.
Might be because it's "occurrences" and not a unique name?

**Comment by tim-band** [comment]
@acholyn isn't that how it has always worked? I'll dig out a very old version and see what's up.

**Comment by acholyn** [comment]
Oh in that case, nothing to worry about! I don't think I noticed it before

**Comment by tim-band** [comment]
The old navigation produced:

Home <- Search <- Search Results <- ugu <- occurrences <- texts <- er₂

before going back to shorter breadcrumb lists. This one does the same.

**Review by acholyn — APPROVED** [review]

**Pull request merged**
